import {
  Box,
  BoxProps,
  chakra,
  Flex,
  Img,
  Stack,
  Text,
} from "@chakra-ui/react";
import { motion } from "framer-motion";
import Head from "next/head";
import { dataset, MediaItem, RawMedia } from "../lib/data";

const MotionBox = motion(Box);
const Video = chakra("video");

const tweets = dataset.tweets.filter(
  (tweet) => !tweet.isReply && tweet.hasMedia && tweet.replies.length > 0
);

// interface MediaProps {
//   media: Media;
// }

const Media = ({ media, ...otherProps }: any) => {
  if (media.type === "video") {
    return (
      <Video {...otherProps}>
        {media.sources.map((src: any) => (
          <source key={src.url} src={src.url} type={src.content_type} />
        ))}
      </Video>
    );
  } else {
    return <Img src={media.sources[0].url} {...otherProps} />;
  }
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box as="main">
        <Box pos="fixed" inset={0} zIndex={-1}>
          <MotionBox
            pos="absolute"
            h="40vw"
            w="40vw"
            left={0}
            top={0}
            bg="pink.300"
            rounded="full"
          />
          <MotionBox
            pos="absolute"
            h="40vw"
            w="40vw"
            right={0}
            bottom={0}
            bg="purple.400"
            rounded="full"
          />
          <Box
            bg="whiteAlpha.700"
            pos="absolute"
            inset={0}
            backdropFilter="blur(30px)"
          />
        </Box>
        {tweets.map((tweet) => (
          <Box key={tweet.id}>
            <Flex flexDir="column" gap={16} mt={16} mb="30vh">
              <Box pos="sticky" top={0} p={16} pb={0}>
                <Box pos="relative" h="300px" w="500px" marginX="auto">
                  <Media
                    media={tweet.primaryMedia}
                    w="100%"
                    h="100%"
                    rounded="2xl"
                    objectFit="cover"
                  />
                </Box>
              </Box>
              <Stack spacing={8} maxW="sm" marginX="auto">
                {tweet.replies.map((mention) => (
                  <Box key={mention.id}>
                    <Text fontSize="md" fontWeight="bold">
                      {mention.author.name}
                    </Text>
                    <Text fontSize="md">{mention.text}</Text>
                  </Box>
                ))}
              </Stack>
            </Flex>
          </Box>
        ))}
      </Box>
    </>
  );
}
